-- ============================================================
--  Accounting — invoices, and the details printed on them
--
--  Run once: Supabase → SQL Editor → New query → paste → Run.
--  Safe to run again.
--
--  Two tables:
--    invoices          one row per invoice, whatever its status
--    invoice_settings  your own details, printed on every invoice
--
--  Both are the owner's alone. No admin, no rep, no team login can
--  read or write them, whatever else they were given.
--
--  An invoice number is handed out by the database itself, so two
--  invoices can never share one, and a number is never reused.
--  Nothing is ever deleted: an invoice that should not stand is
--  marked void and keeps its number.
-- ============================================================

create table if not exists public.invoices (
  id          uuid primary key default gen_random_uuid(),
  number      int  generated by default as identity,
  status      text not null default 'draft',      -- draft · sent · paid · void
  client      jsonb not null default '{}'::jsonb, -- name, address, postal, email
  period      text,                               -- what it covers, e.g. '2026-08'
  issue_date  date,
  due_date    date,
  paid_date   date,
  currency    text not null default 'USD',
  sections    jsonb not null default '[]'::jsonb, -- the tables on the invoice
  pay_link    text,                               -- Wise, or wherever they pay
  notes       text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists invoices_client_idx on public.invoices ((client->>'name'));
create index if not exists invoices_issued_idx on public.invoices (issue_date desc);

create table if not exists public.invoice_settings (
  id          int primary key default 1 check (id = 1),
  content     jsonb,
  updated_at  timestamptz not null default now()
);

insert into public.invoice_settings (id) values (1) on conflict (id) do nothing;

-- ---------- who may touch them: the owner, nobody else ----------
alter table public.invoices enable row level security;
alter table public.invoice_settings enable row level security;

drop policy if exists invoices_read on public.invoices;
create policy invoices_read on public.invoices
  for select to authenticated
  using (public.is_owner());

drop policy if exists invoices_write on public.invoices;
create policy invoices_write on public.invoices
  for insert to authenticated
  with check (public.is_owner());

drop policy if exists invoices_update on public.invoices;
create policy invoices_update on public.invoices
  for update to authenticated
  using (public.is_owner())
  with check (public.is_owner());

drop policy if exists invoice_settings_read on public.invoice_settings;
create policy invoice_settings_read on public.invoice_settings
  for select to authenticated
  using (public.is_owner());

drop policy if exists invoice_settings_write on public.invoice_settings;
create policy invoice_settings_write on public.invoice_settings
  for insert to authenticated
  with check (public.is_owner());

drop policy if exists invoice_settings_update on public.invoice_settings;
create policy invoice_settings_update on public.invoice_settings
  for update to authenticated
  using (public.is_owner())
  with check (public.is_owner());

-- There is deliberately no delete policy on either table: an invoice
-- that was sent is a record, and records are kept.
