/* ============================================================
   clock-cities.js — cities you can search for on the portal clock
   ------------------------------------------------------------
   The browser only knows time zones ("America/Sao_Paulo"), and most
   cities are not one: Rio de Janeiro, Brasília and Curitiba all keep
   São Paulo time. This list maps real cities onto their zone, so the
   clock can be searched the way anyone actually thinks about it.

   Every Brazilian state capital is here, across all four of Brazil's
   time zones, along with the world's main cities. Anything missing is
   still reachable: the search also looks through every time zone the
   browser knows.

   To add one: { name, country, zone } — nothing else needed.
   ============================================================ */

const CLOCK_CITIES = [
  /* ---------- Brazil: Brasília time (UTC−3) ---------- */
  { name: 'São Paulo', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Rio de Janeiro', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Brasília', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Belo Horizonte', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Curitiba', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Porto Alegre', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Florianópolis', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Goiânia', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Vitória', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Campinas', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Santos', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Guarulhos', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Ribeirão Preto', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Uberlândia', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Londrina', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Joinville', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Balneário Camboriú', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { name: 'Palmas', country: 'Brazil', zone: 'America/Araguaina' },
  { name: 'Salvador', country: 'Brazil', zone: 'America/Bahia' },
  { name: 'Feira de Santana', country: 'Brazil', zone: 'America/Bahia' },
  { name: 'Aracaju', country: 'Brazil', zone: 'America/Maceio' },
  { name: 'Maceió', country: 'Brazil', zone: 'America/Maceio' },
  { name: 'Recife', country: 'Brazil', zone: 'America/Recife' },
  { name: 'Olinda', country: 'Brazil', zone: 'America/Recife' },
  { name: 'João Pessoa', country: 'Brazil', zone: 'America/Fortaleza' },
  { name: 'Natal', country: 'Brazil', zone: 'America/Fortaleza' },
  { name: 'Fortaleza', country: 'Brazil', zone: 'America/Fortaleza' },
  { name: 'Teresina', country: 'Brazil', zone: 'America/Fortaleza' },
  { name: 'São Luís', country: 'Brazil', zone: 'America/Fortaleza' },
  { name: 'Belém', country: 'Brazil', zone: 'America/Belem' },
  { name: 'Macapá', country: 'Brazil', zone: 'America/Belem' },

  /* ---------- Brazil: Amazon time (UTC−4) ---------- */
  { name: 'Manaus', country: 'Brazil', zone: 'America/Manaus' },
  { name: 'Cuiabá', country: 'Brazil', zone: 'America/Cuiaba' },
  { name: 'Campo Grande', country: 'Brazil', zone: 'America/Campo_Grande' },
  { name: 'Porto Velho', country: 'Brazil', zone: 'America/Porto_Velho' },
  { name: 'Boa Vista', country: 'Brazil', zone: 'America/Boa_Vista' },

  /* ---------- Brazil: Acre time (UTC−5) and Fernando de Noronha (UTC−2) ---------- */
  { name: 'Rio Branco', country: 'Brazil', zone: 'America/Rio_Branco' },
  { name: 'Fernando de Noronha', country: 'Brazil', zone: 'America/Noronha' },

  /* ---------- rest of the Americas ---------- */
  { name: 'New York', country: 'United States', zone: 'America/New_York' },
  { name: 'Miami', country: 'United States', zone: 'America/New_York' },
  { name: 'Orlando', country: 'United States', zone: 'America/New_York' },
  { name: 'Boston', country: 'United States', zone: 'America/New_York' },
  { name: 'Washington DC', country: 'United States', zone: 'America/New_York' },
  { name: 'Atlanta', country: 'United States', zone: 'America/New_York' },
  { name: 'Chicago', country: 'United States', zone: 'America/Chicago' },
  { name: 'Dallas', country: 'United States', zone: 'America/Chicago' },
  { name: 'Austin', country: 'United States', zone: 'America/Chicago' },
  { name: 'Houston', country: 'United States', zone: 'America/Chicago' },
  { name: 'Nashville', country: 'United States', zone: 'America/Chicago' },
  { name: 'Denver', country: 'United States', zone: 'America/Denver' },
  { name: 'Salt Lake City', country: 'United States', zone: 'America/Denver' },
  { name: 'Phoenix', country: 'United States', zone: 'America/Phoenix' },
  { name: 'Scottsdale', country: 'United States', zone: 'America/Phoenix' },
  { name: 'Los Angeles', country: 'United States', zone: 'America/Los_Angeles' },
  { name: 'San Diego', country: 'United States', zone: 'America/Los_Angeles' },
  { name: 'San Francisco', country: 'United States', zone: 'America/Los_Angeles' },
  { name: 'Las Vegas', country: 'United States', zone: 'America/Los_Angeles' },
  { name: 'Seattle', country: 'United States', zone: 'America/Los_Angeles' },
  { name: 'Honolulu', country: 'United States', zone: 'Pacific/Honolulu' },
  { name: 'Toronto', country: 'Canada', zone: 'America/Toronto' },
  { name: 'Montreal', country: 'Canada', zone: 'America/Toronto' },
  { name: 'Vancouver', country: 'Canada', zone: 'America/Vancouver' },
  { name: 'Calgary', country: 'Canada', zone: 'America/Edmonton' },
  { name: 'Mexico City', country: 'Mexico', zone: 'America/Mexico_City' },
  { name: 'Guadalajara', country: 'Mexico', zone: 'America/Mexico_City' },
  { name: 'Monterrey', country: 'Mexico', zone: 'America/Monterrey' },
  { name: 'Cancún', country: 'Mexico', zone: 'America/Cancun' },
  { name: 'Tulum', country: 'Mexico', zone: 'America/Cancun' },
  { name: 'Buenos Aires', country: 'Argentina', zone: 'America/Argentina/Buenos_Aires' },
  { name: 'Santiago', country: 'Chile', zone: 'America/Santiago' },
  { name: 'Lima', country: 'Peru', zone: 'America/Lima' },
  { name: 'Bogotá', country: 'Colombia', zone: 'America/Bogota' },
  { name: 'Medellín', country: 'Colombia', zone: 'America/Bogota' },
  { name: 'Montevideo', country: 'Uruguay', zone: 'America/Montevideo' },
  { name: 'Asunción', country: 'Paraguay', zone: 'America/Asuncion' },
  { name: 'La Paz', country: 'Bolivia', zone: 'America/La_Paz' },
  { name: 'Quito', country: 'Ecuador', zone: 'America/Guayaquil' },
  { name: 'Caracas', country: 'Venezuela', zone: 'America/Caracas' },
  { name: 'Panama City', country: 'Panama', zone: 'America/Panama' },
  { name: 'San José', country: 'Costa Rica', zone: 'America/Costa_Rica' },
  { name: 'Havana', country: 'Cuba', zone: 'America/Havana' },
  { name: 'Santo Domingo', country: 'Dominican Republic', zone: 'America/Santo_Domingo' },
  { name: 'San Juan', country: 'Puerto Rico', zone: 'America/Puerto_Rico' },

  /* ---------- Europe ---------- */
  { name: 'London', country: 'United Kingdom', zone: 'Europe/London' },
  { name: 'Manchester', country: 'United Kingdom', zone: 'Europe/London' },
  { name: 'Dublin', country: 'Ireland', zone: 'Europe/Dublin' },
  { name: 'Lisbon', country: 'Portugal', zone: 'Europe/Lisbon' },
  { name: 'Porto', country: 'Portugal', zone: 'Europe/Lisbon' },
  { name: 'Madeira', country: 'Portugal', zone: 'Atlantic/Madeira' },
  { name: 'Madrid', country: 'Spain', zone: 'Europe/Madrid' },
  { name: 'Barcelona', country: 'Spain', zone: 'Europe/Madrid' },
  { name: 'Marbella', country: 'Spain', zone: 'Europe/Madrid' },
  { name: 'Ibiza', country: 'Spain', zone: 'Europe/Madrid' },
  { name: 'Canary Islands', country: 'Spain', zone: 'Atlantic/Canary' },
  { name: 'Paris', country: 'France', zone: 'Europe/Paris' },
  { name: 'Nice', country: 'France', zone: 'Europe/Paris' },
  { name: 'Monaco', country: 'Monaco', zone: 'Europe/Monaco' },
  { name: 'Amsterdam', country: 'Netherlands', zone: 'Europe/Amsterdam' },
  { name: 'Brussels', country: 'Belgium', zone: 'Europe/Brussels' },
  { name: 'Berlin', country: 'Germany', zone: 'Europe/Berlin' },
  { name: 'Munich', country: 'Germany', zone: 'Europe/Berlin' },
  { name: 'Frankfurt', country: 'Germany', zone: 'Europe/Berlin' },
  { name: 'Zurich', country: 'Switzerland', zone: 'Europe/Zurich' },
  { name: 'Geneva', country: 'Switzerland', zone: 'Europe/Zurich' },
  { name: 'Milan', country: 'Italy', zone: 'Europe/Rome' },
  { name: 'Rome', country: 'Italy', zone: 'Europe/Rome' },
  { name: 'Vienna', country: 'Austria', zone: 'Europe/Vienna' },
  { name: 'Prague', country: 'Czechia', zone: 'Europe/Prague' },
  { name: 'Warsaw', country: 'Poland', zone: 'Europe/Warsaw' },
  { name: 'Stockholm', country: 'Sweden', zone: 'Europe/Stockholm' },
  { name: 'Oslo', country: 'Norway', zone: 'Europe/Oslo' },
  { name: 'Copenhagen', country: 'Denmark', zone: 'Europe/Copenhagen' },
  { name: 'Helsinki', country: 'Finland', zone: 'Europe/Helsinki' },
  { name: 'Athens', country: 'Greece', zone: 'Europe/Athens' },
  { name: 'Bucharest', country: 'Romania', zone: 'Europe/Bucharest' },
  { name: 'Istanbul', country: 'Turkey', zone: 'Europe/Istanbul' },
  { name: 'Moscow', country: 'Russia', zone: 'Europe/Moscow' },
  { name: 'Kyiv', country: 'Ukraine', zone: 'Europe/Kyiv' },
  { name: 'Budapest', country: 'Hungary', zone: 'Europe/Budapest' },

  /* ---------- Middle East and Africa ---------- */
  { name: 'Dubai', country: 'United Arab Emirates', zone: 'Asia/Dubai' },
  { name: 'Abu Dhabi', country: 'United Arab Emirates', zone: 'Asia/Dubai' },
  { name: 'Doha', country: 'Qatar', zone: 'Asia/Qatar' },
  { name: 'Riyadh', country: 'Saudi Arabia', zone: 'Asia/Riyadh' },
  { name: 'Tel Aviv', country: 'Israel', zone: 'Asia/Jerusalem' },
  { name: 'Cairo', country: 'Egypt', zone: 'Africa/Cairo' },
  { name: 'Casablanca', country: 'Morocco', zone: 'Africa/Casablanca' },
  { name: 'Marrakesh', country: 'Morocco', zone: 'Africa/Casablanca' },
  { name: 'Lagos', country: 'Nigeria', zone: 'Africa/Lagos' },
  { name: 'Nairobi', country: 'Kenya', zone: 'Africa/Nairobi' },
  { name: 'Johannesburg', country: 'South Africa', zone: 'Africa/Johannesburg' },
  { name: 'Cape Town', country: 'South Africa', zone: 'Africa/Johannesburg' },

  /* ---------- Asia and Oceania ---------- */
  { name: 'Mumbai', country: 'India', zone: 'Asia/Kolkata' },
  { name: 'Delhi', country: 'India', zone: 'Asia/Kolkata' },
  { name: 'Bangalore', country: 'India', zone: 'Asia/Kolkata' },
  { name: 'Karachi', country: 'Pakistan', zone: 'Asia/Karachi' },
  { name: 'Bangkok', country: 'Thailand', zone: 'Asia/Bangkok' },
  { name: 'Phuket', country: 'Thailand', zone: 'Asia/Bangkok' },
  { name: 'Ho Chi Minh City', country: 'Vietnam', zone: 'Asia/Ho_Chi_Minh' },
  { name: 'Singapore', country: 'Singapore', zone: 'Asia/Singapore' },
  { name: 'Kuala Lumpur', country: 'Malaysia', zone: 'Asia/Kuala_Lumpur' },
  { name: 'Bali', country: 'Indonesia', zone: 'Asia/Makassar' },
  { name: 'Jakarta', country: 'Indonesia', zone: 'Asia/Jakarta' },
  { name: 'Manila', country: 'Philippines', zone: 'Asia/Manila' },
  { name: 'Hong Kong', country: 'Hong Kong', zone: 'Asia/Hong_Kong' },
  { name: 'Shanghai', country: 'China', zone: 'Asia/Shanghai' },
  { name: 'Beijing', country: 'China', zone: 'Asia/Shanghai' },
  { name: 'Taipei', country: 'Taiwan', zone: 'Asia/Taipei' },
  { name: 'Seoul', country: 'South Korea', zone: 'Asia/Seoul' },
  { name: 'Tokyo', country: 'Japan', zone: 'Asia/Tokyo' },
  { name: 'Sydney', country: 'Australia', zone: 'Australia/Sydney' },
  { name: 'Melbourne', country: 'Australia', zone: 'Australia/Melbourne' },
  { name: 'Brisbane', country: 'Australia', zone: 'Australia/Brisbane' },
  { name: 'Perth', country: 'Australia', zone: 'Australia/Perth' },
  { name: 'Auckland', country: 'New Zealand', zone: 'Pacific/Auckland' },
  /* ---------- more of the Americas ---------- */
  { name: 'Philadelphia', country: 'United States', zone: 'America/New_York' },
  { name: 'Detroit', country: 'United States', zone: 'America/Detroit' },
  { name: 'Charlotte', country: 'United States', zone: 'America/New_York' },
  { name: 'Tampa', country: 'United States', zone: 'America/New_York' },
  { name: 'Fort Lauderdale', country: 'United States', zone: 'America/New_York' },
  { name: 'West Palm Beach', country: 'United States', zone: 'America/New_York' },
  { name: 'Minneapolis', country: 'United States', zone: 'America/Chicago' },
  { name: 'Kansas City', country: 'United States', zone: 'America/Chicago' },
  { name: 'New Orleans', country: 'United States', zone: 'America/Chicago' },
  { name: 'San Antonio', country: 'United States', zone: 'America/Chicago' },
  { name: 'Portland', country: 'United States', zone: 'America/Los_Angeles' },
  { name: 'Sacramento', country: 'United States', zone: 'America/Los_Angeles' },
  { name: 'Anchorage', country: 'United States', zone: 'America/Anchorage' },
  { name: 'Ottawa', country: 'Canada', zone: 'America/Toronto' },
  { name: 'Quebec City', country: 'Canada', zone: 'America/Toronto' },
  { name: 'Winnipeg', country: 'Canada', zone: 'America/Winnipeg' },
  { name: 'Halifax', country: 'Canada', zone: 'America/Halifax' },
  { name: 'Tijuana', country: 'Mexico', zone: 'America/Tijuana' },
  { name: 'Puerto Vallarta', country: 'Mexico', zone: 'America/Mexico_City' },
  { name: 'Guatemala City', country: 'Guatemala', zone: 'America/Guatemala' },
  { name: 'San Salvador', country: 'El Salvador', zone: 'America/El_Salvador' },
  { name: 'Tegucigalpa', country: 'Honduras', zone: 'America/Tegucigalpa' },
  { name: 'Managua', country: 'Nicaragua', zone: 'America/Managua' },
  { name: 'Kingston', country: 'Jamaica', zone: 'America/Jamaica' },
  { name: 'Nassau', country: 'Bahamas', zone: 'America/Nassau' },
  { name: 'Bridgetown', country: 'Barbados', zone: 'America/Barbados' },
  { name: 'Port of Spain', country: 'Trinidad and Tobago', zone: 'America/Port_of_Spain' },
  { name: 'Cali', country: 'Colombia', zone: 'America/Bogota' },
  { name: 'Cartagena', country: 'Colombia', zone: 'America/Bogota' },
  { name: 'Guayaquil', country: 'Ecuador', zone: 'America/Guayaquil' },
  { name: 'Cusco', country: 'Peru', zone: 'America/Lima' },
  { name: 'Córdoba', country: 'Argentina', zone: 'America/Argentina/Cordoba' },
  { name: 'Mendoza', country: 'Argentina', zone: 'America/Argentina/Mendoza' },
  { name: 'Rosario', country: 'Argentina', zone: 'America/Argentina/Buenos_Aires' },
  { name: 'Punta del Este', country: 'Uruguay', zone: 'America/Montevideo' },
  { name: 'Santa Cruz de la Sierra', country: 'Bolivia', zone: 'America/La_Paz' },

  /* ---------- more of Europe ---------- */
  { name: 'Edinburgh', country: 'United Kingdom', zone: 'Europe/London' },
  { name: 'Birmingham', country: 'United Kingdom', zone: 'Europe/London' },
  { name: 'Glasgow', country: 'United Kingdom', zone: 'Europe/London' },
  { name: 'Rotterdam', country: 'Netherlands', zone: 'Europe/Amsterdam' },
  { name: 'Hamburg', country: 'Germany', zone: 'Europe/Berlin' },
  { name: 'Cologne', country: 'Germany', zone: 'Europe/Berlin' },
  { name: 'Düsseldorf', country: 'Germany', zone: 'Europe/Berlin' },
  { name: 'Stuttgart', country: 'Germany', zone: 'Europe/Berlin' },
  { name: 'Basel', country: 'Switzerland', zone: 'Europe/Zurich' },
  { name: 'Lugano', country: 'Switzerland', zone: 'Europe/Zurich' },
  { name: 'Lyon', country: 'France', zone: 'Europe/Paris' },
  { name: 'Marseille', country: 'France', zone: 'Europe/Paris' },
  { name: 'Bordeaux', country: 'France', zone: 'Europe/Paris' },
  { name: 'Valencia', country: 'Spain', zone: 'Europe/Madrid' },
  { name: 'Seville', country: 'Spain', zone: 'Europe/Madrid' },
  { name: 'Málaga', country: 'Spain', zone: 'Europe/Madrid' },
  { name: 'Palma de Mallorca', country: 'Spain', zone: 'Europe/Madrid' },
  { name: 'Naples', country: 'Italy', zone: 'Europe/Rome' },
  { name: 'Turin', country: 'Italy', zone: 'Europe/Rome' },
  { name: 'Florence', country: 'Italy', zone: 'Europe/Rome' },
  { name: 'Venice', country: 'Italy', zone: 'Europe/Rome' },
  { name: 'Zagreb', country: 'Croatia', zone: 'Europe/Zagreb' },
  { name: 'Split', country: 'Croatia', zone: 'Europe/Zagreb' },
  { name: 'Belgrade', country: 'Serbia', zone: 'Europe/Belgrade' },
  { name: 'Sofia', country: 'Bulgaria', zone: 'Europe/Sofia' },
  { name: 'Ljubljana', country: 'Slovenia', zone: 'Europe/Ljubljana' },
  { name: 'Bratislava', country: 'Slovakia', zone: 'Europe/Bratislava' },
  { name: 'Tallinn', country: 'Estonia', zone: 'Europe/Tallinn' },
  { name: 'Riga', country: 'Latvia', zone: 'Europe/Riga' },
  { name: 'Vilnius', country: 'Lithuania', zone: 'Europe/Vilnius' },
  { name: 'Luxembourg', country: 'Luxembourg', zone: 'Europe/Luxembourg' },
  { name: 'Valletta', country: 'Malta', zone: 'Europe/Malta' },
  { name: 'Nicosia', country: 'Cyprus', zone: 'Asia/Nicosia' },
  { name: 'Reykjavík', country: 'Iceland', zone: 'Atlantic/Reykjavik' },
  { name: 'Andorra', country: 'Andorra', zone: 'Europe/Andorra' },
  { name: 'Saint Petersburg', country: 'Russia', zone: 'Europe/Moscow' },

  /* ---------- more of the Middle East and Africa ---------- */
  { name: 'Sharjah', country: 'United Arab Emirates', zone: 'Asia/Dubai' },
  { name: 'Ras Al Khaimah', country: 'United Arab Emirates', zone: 'Asia/Dubai' },
  { name: 'Jeddah', country: 'Saudi Arabia', zone: 'Asia/Riyadh' },
  { name: 'Mecca', country: 'Saudi Arabia', zone: 'Asia/Riyadh' },
  { name: 'Kuwait City', country: 'Kuwait', zone: 'Asia/Kuwait' },
  { name: 'Manama', country: 'Bahrain', zone: 'Asia/Bahrain' },
  { name: 'Muscat', country: 'Oman', zone: 'Asia/Muscat' },
  { name: 'Amman', country: 'Jordan', zone: 'Asia/Amman' },
  { name: 'Beirut', country: 'Lebanon', zone: 'Asia/Beirut' },
  { name: 'Jerusalem', country: 'Israel', zone: 'Asia/Jerusalem' },
  { name: 'Baghdad', country: 'Iraq', zone: 'Asia/Baghdad' },
  { name: 'Tehran', country: 'Iran', zone: 'Asia/Tehran' },
  { name: 'Baku', country: 'Azerbaijan', zone: 'Asia/Baku' },
  { name: 'Tbilisi', country: 'Georgia', zone: 'Asia/Tbilisi' },
  { name: 'Yerevan', country: 'Armenia', zone: 'Asia/Yerevan' },
  { name: 'Tashkent', country: 'Uzbekistan', zone: 'Asia/Tashkent' },
  { name: 'Almaty', country: 'Kazakhstan', zone: 'Asia/Almaty' },
  { name: 'Alexandria', country: 'Egypt', zone: 'Africa/Cairo' },
  { name: 'Tunis', country: 'Tunisia', zone: 'Africa/Tunis' },
  { name: 'Algiers', country: 'Algeria', zone: 'Africa/Algiers' },
  { name: 'Accra', country: 'Ghana', zone: 'Africa/Accra' },
  { name: 'Abidjan', country: 'Ivory Coast', zone: 'Africa/Abidjan' },
  { name: 'Dakar', country: 'Senegal', zone: 'Africa/Dakar' },
  { name: 'Addis Ababa', country: 'Ethiopia', zone: 'Africa/Addis_Ababa' },
  { name: 'Kampala', country: 'Uganda', zone: 'Africa/Kampala' },
  { name: 'Dar es Salaam', country: 'Tanzania', zone: 'Africa/Dar_es_Salaam' },
  { name: 'Kigali', country: 'Rwanda', zone: 'Africa/Kigali' },
  { name: 'Luanda', country: 'Angola', zone: 'Africa/Luanda' },
  { name: 'Maputo', country: 'Mozambique', zone: 'Africa/Maputo' },
  { name: 'Durban', country: 'South Africa', zone: 'Africa/Johannesburg' },
  { name: 'Pretoria', country: 'South Africa', zone: 'Africa/Johannesburg' },
  { name: 'Mauritius', country: 'Mauritius', zone: 'Indian/Mauritius' },

  /* ---------- more of Asia and Oceania ---------- */
  { name: 'Kathmandu', country: 'Nepal', zone: 'Asia/Katmandu' },
  { name: 'Colombo', country: 'Sri Lanka', zone: 'Asia/Colombo' },
  { name: 'Dhaka', country: 'Bangladesh', zone: 'Asia/Dhaka' },
  { name: 'Malé', country: 'Maldives', zone: 'Indian/Maldives' },
  { name: 'Chennai', country: 'India', zone: 'Asia/Kolkata' },
  { name: 'Hyderabad', country: 'India', zone: 'Asia/Kolkata' },
  { name: 'Kolkata', country: 'India', zone: 'Asia/Kolkata' },
  { name: 'Pune', country: 'India', zone: 'Asia/Kolkata' },
  { name: 'Goa', country: 'India', zone: 'Asia/Kolkata' },
  { name: 'Lahore', country: 'Pakistan', zone: 'Asia/Karachi' },
  { name: 'Islamabad', country: 'Pakistan', zone: 'Asia/Karachi' },
  { name: 'Hanoi', country: 'Vietnam', zone: 'Asia/Ho_Chi_Minh' },
  { name: 'Da Nang', country: 'Vietnam', zone: 'Asia/Ho_Chi_Minh' },
  { name: 'Phnom Penh', country: 'Cambodia', zone: 'Asia/Phnom_Penh' },
  { name: 'Siem Reap', country: 'Cambodia', zone: 'Asia/Phnom_Penh' },
  { name: 'Vientiane', country: 'Laos', zone: 'Asia/Vientiane' },
  { name: 'Yangon', country: 'Myanmar', zone: 'Asia/Rangoon' },
  { name: 'Ulaanbaatar', country: 'Mongolia', zone: 'Asia/Ulaanbaatar' },
  { name: 'Chiang Mai', country: 'Thailand', zone: 'Asia/Bangkok' },
  { name: 'Osaka', country: 'Japan', zone: 'Asia/Tokyo' },
  { name: 'Kyoto', country: 'Japan', zone: 'Asia/Tokyo' },
  { name: 'Busan', country: 'South Korea', zone: 'Asia/Seoul' },
  { name: 'Shenzhen', country: 'China', zone: 'Asia/Shanghai' },
  { name: 'Guangzhou', country: 'China', zone: 'Asia/Shanghai' },
  { name: 'Chengdu', country: 'China', zone: 'Asia/Shanghai' },
  { name: 'Macau', country: 'Macau', zone: 'Asia/Macau' },
  { name: 'Adelaide', country: 'Australia', zone: 'Australia/Adelaide' },
  { name: 'Canberra', country: 'Australia', zone: 'Australia/Sydney' },
  { name: 'Gold Coast', country: 'Australia', zone: 'Australia/Brisbane' },
  { name: 'Cairns', country: 'Australia', zone: 'Australia/Brisbane' },
  { name: 'Darwin', country: 'Australia', zone: 'Australia/Darwin' },
  { name: 'Hobart', country: 'Australia', zone: 'Australia/Hobart' },
  { name: 'Wellington', country: 'New Zealand', zone: 'Pacific/Auckland' },
  { name: 'Christchurch', country: 'New Zealand', zone: 'Pacific/Auckland' },
  { name: 'Suva', country: 'Fiji', zone: 'Pacific/Fiji' },
  { name: 'Guam', country: 'Guam', zone: 'Pacific/Guam' },
  { name: 'Papeete', country: 'French Polynesia', zone: 'Pacific/Tahiti' },
  { name: 'UTC', country: 'Coordinated Universal Time', zone: 'UTC' }
];
